INSERT INTO USER_ROLE (ID, NAME) VALUES (1, 'ROLE_READER');
INSERT INTO USER_ROLE (ID, NAME) VALUES (2, 'ROLE_BASIC');
INSERT INTO USER_ROLE (ID, NAME) VALUES (3, 'ROLE_ADVANCED');
INSERT INTO USER_ROLE (ID, NAME) VALUES (4, 'ROLE_ADMIN');

INSERT INTO USER_ (ID, EMAIL, PASSWORD, POINTS, ROLE_ID)
VALUES (1, 'reader@email.com', '$2a$10$kjI4cvr4fp9J7ddQdL6xc.LR2zsCLLrNl9GtxGLnCmwDIfzCYi0Wy', 0, 1);

INSERT INTO USER_ (ID, EMAIL, PASSWORD, POINTS, ROLE_ID)
VALUES (2, 'basic@email.com', '$2a$10$kjI4cvr4fp9J7ddQdL6xc.LR2zsCLLrNl9GtxGLnCmwDIfzCYi0Wy', 20, 2);

INSERT INTO USER_ (ID, EMAIL, PASSWORD, POINTS, ROLE_ID)
VALUES (3, 'advanced@email.com', '$2a$10$kjI4cvr4fp9J7ddQdL6xc.LR2zsCLLrNl9GtxGLnCmwDIfzCYi0Wy', 1000, 3);

INSERT INTO USER_ (ID, EMAIL, PASSWORD, POINTS, ROLE_ID)
VALUES (4, 'admin@email.com', '$2a$10$kjI4cvr4fp9J7ddQdL6xc.LR2zsCLLrNl9GtxGLnCmwDIfzCYi0Wy', 0, 4);
